//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_DEMOGRAPHICSPAGE            102
#define IDD_CONTACTSPAGE                103
#define IDD_LOGIN                       104
#define IDD_STUDENTCHOOSER              106
#define IDD_STUDENTEDIT                 107
#define IDD_EVALUATIONSPAGE             110
#define IDD_SERVICESPAGE                111
#define IDD_ASSESSMENTSPAGE             112
#define IDD_REFERRALSPAGE               113
#define IDD_LISTEDIT                    120
#define IDD_ADDLISTITEM                 121
#define IDD_USERLIST                    122
#define IDD_USEREDIT                    123
#define IDD_NEWSTUDENTOPTIONS           124
#define IDR_MAINWINDOW                  129
#define IDD_BACKUP                      131
#define IDI_STUDENTINFO                 137
#define IDI_CHECK                       140
#define IDD_RESTORE                     141
#define IDD_CONNECTIONOPTIONS           143
#define IDD_ABOUT                       147
#define IDD_ASSESSMENTMODS              149
#define IDD_DISTRIBUTIONSPAGE           150
#define IDI_NOCHECK                     151
#define IDC_ADDEVALUATION               1004
#define IDC_REMOVEEVALUATION            1005
#define IDC_MOTHERHOMEPHONE             1006
#define IDC_USERNAME                    1007
#define IDC_PASSWORD                    1008
#define IDC_SEARCHLASTNAME              1009
#define IDC_SEARCHFIRSTNAME             1010
#define IDC_SEARCHSSN                   1011
#define IDC_SEARCHCHECK                 1012
#define IDC_STUDENTLIST                 1013
#define IDC_EVALUATIONSREQUESTED        1013
#define IDC_OPENSTUDENT                 1014
#define IDC_SEARCHBUTTON                1015
#define IDC_NEWSTUDENT                  1016
#define IDC_BIRTHDATE                   1017
#define IDC_LASTNAME                    1019
#define IDC_DEMOGRAPHICSTAB             1020
#define IDC_CONTACTSTAB                 1021
#define IDC_SERVICESTAB                 1022
#define IDC_REFERRALSTAB                1023
#define IDC_ASSESSMENTSTAB              1024
#define IDC_EVALUATIONSTAB              1025
#define IDC_FIRSTNAME                   1026
#define IDC_MIDDLENAME                  1027
#define IDC_SSN                         1028
#define IDC_DISTRIBUTIONSTAB            1029
#define IDC_ESYSERVICES                 1030
#define IDC_PRIMARYDISABILITYCODE       1031
#define IDC_SECONDARYDISABILITYCODE     1032
#define IDC_TERTIARYDISABILITYCODE      1033
#define IDC_LASTARDDATE                 1034
#define IDC_LASTANNUALREVIEWDATE        1035
#define IDC_ITPDATE                     1036
#define IDC_IEPSTARTDATE                1037
#define IDC_FATHERFIRSTNAME             1038
#define IDC_FATHERLASTNAME              1039
#define IDC_FATHERADDRESS               1040
#define IDC_FATHERCITY                  1041
#define IDC_FATHERSTATE                 1042
#define IDC_FATHERZIPCODE               1043
#define IDC_DEMOGRAPHICSCOMMENTS        1044
#define IDC_INSTRUCTIONALSETTING        1045
#define IDC_REFERRINGCAMPUS             1046
#define IDC_EVALUATIONREQUESTLIST       1047
#define IDC_ADDRESS                     1052
#define IDC_CITY                        1053
#define IDC_STATE                       1054
#define IDC_MAILINGADDRESS              1055
#define IDC_HOMEPHONE                   1056
#define IDC_MAILINGCITY                 1057
#define IDC_STATUSDATE                  1058
#define IDC_STATUS                      1059
#define IDC_ELIGIBILITY                 1060
#define IDC_GENDER                      1061
#define IDC_ETHNICITY                   1062
#define IDC_CAMPUS                      1063
#define IDC_GRADE                       1064
#define IDC_BIPDATE                     1065
#define IDC_MAILINGSTATE                1065
#define IDC_IEPENDDATE                  1066
#define IDC_MOTHEREMAIL                 1067
#define IDC_FATHERHOMEPHONE             1068
#define IDC_FATHERCELLPHONE             1069
#define IDC_FATHEREMAIL                 1070
#define IDC_CONTACTSCOMMENTS            1077
#define IDC_MEDICALLYFRAGILE            1078
#define IDC_INSTRUCTIONALSERVICES       1079
#define IDC_RELATEDSERVICES             1080
#define IDC_ENGLISHLAASSESSMENT         1081
#define IDC_K2READINGASSESSMENT         1085
#define IDC_READINGASSESSMENT           1086
#define IDC_MATHASSESSMENT              1087
#define IDC_WRITINGASSESSMENT           1088
#define IDC_SCIENCEASSESSMENT           1089
#define IDC_SOCIALSTUDIESASSESSMENT     1090
#define IDC_ASSESSMENTSCOMMENTS         1093
#define IDC_MOTHERFIRSTNAME             1108
#define IDC_MOTHERLASTNAME              1109
#define IDC_MOTHERADDRESS               1110
#define IDC_MOTHERCITY                  1111
#define IDC_MOTHERSTATE                 1112
#define IDC_MOTHERZIPCODE               1113
#define IDC_MOTHERWORKPHONE             1114
#define IDC_MOTHERCELLPHONE             1115
#define IDC_FATHERWORKPHONE             1116
#define IDC_CHRONAGE                    1117
#define IDC_ZIPCODE                     1120
#define IDC_PRIMARYDISABILITY           1121
#define IDC_MAILINGZIPCODE              1121
#define IDC_SECONDARYDISABILITY         1122
#define IDC_TERTIARYDISABILITY          1123
#define IDC_MULTIPLEDISABILITIES        1124
#define IDC_EVALUATIONS                 1125
#define IDC_EVALUATIONSCOMMENTS         1126
#define IDC_REFERRALDATE                1127
#define IDC_EVALUATIONDUEDATE           1128
#define IDC_ARDDUEDATE                  1129
#define IDC_EVALUATIONCOMPLETEDDATE     1130
#define IDC_ARDCOMPLETEDDATE            1131
#define IDC_REFERRALELIGIBLE            1132
#define IDC_REFERRALSCOMMENTS           1133
#define IDC_INSTRUCTIONALSETTINGCODE    1134
#define IDC_SERVICESCOMMENTS            1136
#define IDC_SEARCHSCHOOLYEAR            1140
#define IDC_SCHOOLYEAR                  1141
#define IDC_LIST                        1147
#define IDC_ADDLISTITEM                 1148
#define IDC_REMOVELISTITEM              1149
#define IDC_LISTID                      1150
#define IDC_LISTDESC                    1151
#define IDC_USERLIST                    1152
#define IDC_NEWUSERBUTTON               1153
#define IDC_DELETEUSERBUTTON            1154
#define IDC_PASSWORD1                   1156
#define IDC_PASSWORD2                   1157
#define IDC_CANWRITE                    1158
#define IDC_ISADMINOLD                  1159
#define IDC_CREATENEW                   1160
#define IDC_IMPORT                      1161
#define IDC_IMPORTSSN                   1162
#define IDC_MEDICAID                    1163
#define IDC_BACKUPPROGRESS              1167
#define IDC_RESTOREPROGRESS             1206
#define IDC_RESTORESQL                  1207
#define IDC_SHOWNEWOPTIONS              1208
#define IDC_DSNRADIO                    1209
#define IDC_ACCESSRADIO                 1210
#define IDC_SQLRADIO                    1211
#define IDC_DSN                         1212
#define IDC_BROWSE                      1213
#define IDC_ACCESS                      1214
#define IDC_SQLSERVER                   1215
#define IDC_SQLADDRESS                  1216
#define IDC_SQLDATABASE                 1217
#define IDC_DATABASE                    1218
#define IDC_OPTIONS                     1219
#define IDC_PREFIX                      1220
#define IDC_K2READINGMODS               1221
#define IDC_READINGBASELINEGRADE        1223
#define IDC_READINGMODS                 1226
#define IDC_MATHMODS                    1227
#define IDC_WRITINGMODS                 1228
#define IDC_SCIENCEMODS                 1229
#define IDC_SOCIALSTUDIESMODS           1230
#define IDC_ENGLISHLAMODS               1231
#define IDC_READINGGRADE                1235
#define IDC_READINGBASELINEACH          1236
#define IDC_READINGACH                  1237
#define IDC_MATHBASELINEGRADE           1238
#define IDC_MATHGRADE                   1239
#define IDC_MATHBASELINEACH             1240
#define IDC_MATHACH                     1241
#define IDC_WRITINGGRADE                1243
#define IDC_WRITINGACH                  1245
#define IDC_SCIENCEBASELINEGRADE        1246
#define IDC_SCIENCEGRADE                1247
#define IDC_SCIENCEBASELINEACH          1248
#define IDC_SCIENCEACH                  1249
#define IDC_SOCIALSTUDIESBASELINEGRADE  1250
#define IDC_SOCIALSTUDIESGRADE          1251
#define IDC_SOCIALSTUDIESBASELINEACH    1252
#define IDC_SOCIALSTUDIESACH            1253
#define IDC_ENGLISHLABASELINEGRADE      1254
#define IDC_ENGLISHLAGRADE              1255
#define IDC_ENGLISHLABASELINEACH        1256
#define IDC_ENGLISHLAACH                1257
#define IDC_READINGBASELINEYEAR         1272
#define IDC_READINGARDEXP               1273
#define IDC_MATHBASELINEYEAR            1274
#define IDC_MATHARDEXP                  1275
#define IDC_WRITINGARDEXP               1277
#define IDC_SCIENCEBASELINEYEAR         1278
#define IDC_SCIENCEARDEXP               1279
#define IDC_SOCIALSTUDIESBASELINEYEAR   1280
#define IDC_SOCIALSTUDIESARDEXP         1281
#define IDC_ENGLISHLABASELINEYEAR       1282
#define IDC_ENGLISHLAARDEXP             1283
#define IDC_DISTRICTASSESSMENT          1290
#define IDC_MODLIST                     1296
#define IDC_ASSESSMENTARDDATE           1297
#define IDC_DISTRIBUTIONS               1301
#define IDC_DISTRIBUTIONSCOMMENTS       1302
#define IDC_COPYADDRESSDOWN             1303
#define IDC_COPYADDRESSUP               1304
#define IDC_BACKUPTABLELIST             1308
#define ID_EDITLIST_CAMPUS              40015
#define ID_EDITLIST_GRADE               40016
#define ID_EDITLIST_STATUS              40017
#define ID_EDITLIST_ELIGIBILITY         40018
#define ID_EDITLIST_GENDER              40019
#define ID_EDITLIST_ETHNICITY           40020
#define ID_EDITLIST_INSTRUCTIONALSETTING 40021
#define ID_EDITLIST_DISABILITY          40022
#define ID_EDITLIST_ASSESSMENT          40023
#define ID_EDITLIST_REFERRALELIGIBLE    40024
#define ID_EDITLIST_EVALUATIONTYPE      40025
#define ID_EDITLIST_EVALUATIONELIGIBLE  40026
#define ID_EDITLIST_SERVICETYPE         40027
#define ID_EDITLIST_ESYSERVICETYPE      40028
#define ID_EDITLIST_INSTRUCTIONALSERVICETYPE 40029
#define ID_EDITLIST_RELATEDSERVICETYPE  40030
#define ID_ADMIN_EDITUSERS              40031
#define ID_HELP_ABOUT                   40032
#define ID_WINDOW_CLOSE                 40033
#define ID_WINDOW_CLOSEALL              40034
#define ID_WINDOW_PREVIOUS              40035
#define ID_WINDOW_NEXT                  40036
#define ID_FILE_SAVEALL                 40042
#define ID_VIEW_STUDENTCHOOSER          40044
#define ID_FILE_DELETE                  40046
#define ID_TOOLS_QUERY                  40048
#define ID_TOOLS_BACKUP                 40058
#define ID_TOOLS_RESTORE                40059
#define ID_EDITLIST_SCHOOLYEAR          40060
#define ID_FILE_SHOWOPTIONSONNEW        40061
#define ID_EDITLIST_ACHLEVEL            40062
#define ID_EDITLIST_GRADELEVEL          40063
#define ID_EDITLIST_ASSESSMENTMOD       40065
#define ID_EDITLIST_DOCUMENT            40066
#define ID_EDITLIST_DISTRIBUTIONMETHOD  40067
#define ID_EDITLIST_INITIALDISTRIBUTION 40068

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         40069
#define _APS_NEXT_CONTROL_VALUE         1309
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
